'use client'
import { AuthProvider } from '@/context/AuthProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { usePathname } from 'next/navigation';
import { checkIsPublicRoute } from '@/functions/check-is-public-route'
import PrivateRoute from '@/app/app/components/PrivateRoute'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Parnaioca',
  description: 'Generated by create next app',
  icons:{
    icon:['../../public/favicon.ico']
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pathname = usePathname();

  const isPublicPage = checkIsPublicRoute(pathname!);

  console.log(isPublicPage);

  return (
    <html lang="en">
      <header>
        <link rel="stylesheet" href="../../public/favicon.ico" className="w-full h-0"/>
        <title>Parnaioca</title>

      </header>
      <AuthProvider>
        <body className={inter.className}>

          {isPublicPage && children}

          {!isPublicPage && (
            <>
              <PrivateRoute>{children}</PrivateRoute>
            </>
          )}
        </body>
      </AuthProvider>
    </html>
  )
}
